-- MySQL Script generated by MySQL Workbench
-- 03/01/18 17:06:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema awstock
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema awstock
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `awstock` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `awstock` ;

-- -----------------------------------------------------
-- Table `awstock`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awstock`.`user` (
  `usreId` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `phone` VARCHAR(45) NULL COMMENT '',
  `address` VARCHAR(255) NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `password` VARCHAR(255) NULL COMMENT '',
  `status` VARCHAR(45) NULL COMMENT '',
  `userType` VARCHAR(5) NULL COMMENT '',
  PRIMARY KEY (`usreId`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `awstock`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awstock`.`category` (
  `categoryId` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `categoryName` VARCHAR(45) NULL COMMENT '',
  `categoryDesc` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`categoryId`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `awstock`.`color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awstock`.`color` (
  `colorId` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `colorName` VARCHAR(45) NULL COMMENT '',
  `colorDescription` VARCHAR(45) NULL COMMENT '',
  `colorType` VARCHAR(15) NULL COMMENT '',
  PRIMARY KEY (`colorId`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `awstock`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awstock`.`product` (
  `productId` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `status` VARCHAR(45) NULL COMMENT '',
  `fkcategoryId` INT NOT NULL COMMENT '',
  `style` VARCHAR(45) NULL COMMENT '',
  `sku` VARCHAR(45) NULL COMMENT '',
  `ean` VARCHAR(45) NULL COMMENT '',
  `productName` VARCHAR(45) NULL COMMENT '',
  `productDesc` MEDIUMTEXT NULL COMMENT '',
  `brand` VARCHAR(25) NULL COMMENT '',
  `color` VARCHAR(25) NULL COMMENT '',
  `colorDesc` MEDIUMTEXT NULL COMMENT '',
  `size` VARCHAR(5) NULL COMMENT '',
  `swatchImage` MEDIUMTEXT NULL COMMENT '',
  `mainImage` MEDIUMTEXT NULL COMMENT '',
  `outfit` MEDIUMTEXT NULL COMMENT '',
  `image2` MEDIUMTEXT NULL COMMENT '',
  `image3` MEDIUMTEXT NULL COMMENT '',
  `image4` MEDIUMTEXT NULL COMMENT '',
  `runtosize` VARCHAR(45) NULL COMMENT '',
  `care` VARCHAR(45) NULL COMMENT '',
  `price` INT NULL COMMENT '',
  `stockQty` INT NULL COMMENT '',
  `minQtyAlert` INT NULL COMMENT '',
  `LastExportedBy` INT NULL COMMENT '',
  `LastExportedDate` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`productId`)  COMMENT '',
  INDEX `fk_product_category1_idx` (`fkcategoryId` ASC)  COMMENT '',
  CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`fkcategoryId`)
    REFERENCES `awstock`.`category` (`categoryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `awstock`.`fileTransfer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awstock`.`fileTransfer` (
  `transferId` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fileName` VARCHAR(45) NULL COMMENT '',
  `fileType` VARCHAR(15) NULL COMMENT '',
  `createDate` DATETIME NULL COMMENT '',
  `createBy` INT NULL COMMENT '',
  PRIMARY KEY (`transferId`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `awstock`.`offer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awstock`.`offer` (
  `offerId` INT NOT NULL COMMENT '',
  `fkproductId` INT NOT NULL COMMENT '',
  `disPrice` VARCHAR(45) NULL COMMENT '',
  `disStartPrice` VARCHAR(45) NULL COMMENT '',
  `disEndPrice` VARCHAR(45) NULL COMMENT '',
  `stat` VARCHAR(45) NULL COMMENT '',
  `prod-id-type` VARCHAR(45) NULL COMMENT '',
  `status` VARCHAR(45) NULL COMMENT '',
  `lastExportedBy` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `lastExportedDate` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`offerId`)  COMMENT '',
  INDEX `fk_offer_product1_idx` (`fkproductId` ASC)  COMMENT '',
  CONSTRAINT `fk_offer_product1`
    FOREIGN KEY (`fkproductId`)
    REFERENCES `awstock`.`product` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `awstock`.`size`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awstock`.`size` (
  `sizeId` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `sizeName` VARCHAR(45) NULL COMMENT '',
  `sizeDescription` VARCHAR(45) NULL COMMENT '',
  `sizeType` VARCHAR(15) NULL COMMENT '',
  PRIMARY KEY (`sizeId`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `awstock`.`care`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awstock`.`care` (
  `careId` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `careName` VARCHAR(45) NULL COMMENT '',
  `careDescription` VARCHAR(45) NULL COMMENT '',
  `careType` VARCHAR(15) NULL COMMENT '',
  PRIMARY KEY (`careId`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `awstock`.`runToSize`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awstock`.`runToSize` (
  `runToSizeId` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `runToSizeName` VARCHAR(45) NULL COMMENT '',
  `runToSizeDescription` VARCHAR(45) NULL COMMENT '',
  `runToSizeType` VARCHAR(15) NULL COMMENT '',
  PRIMARY KEY (`runToSizeId`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
